import type { CurationPeriod } from "./types";

/**
 * Curated periods and artists for the seed pipeline.
 *
 * Generated from the live Wikipedia/Commons verification workflow
 * (15/15 periods verified). Artists are listed in rank order; up to 6
 * per period — the seed's live validation picks the final 3-4.
 * Unverified or license-gated artists (cannot yield ~8 free work
 * images) were dropped.
 */
export const CURATION: CurationPeriod[] = [
  {
    slug: "medieval-gothic",
    name: "Medieval & Gothic",
    wikipediaTitle: "Gothic art",
    startYear: 1200,
    endYear: 1420,
    color: "#4a5fb8",
    laneY: 500,
    artists: [
      {
        name: "Giotto di Bondone",
        wikipediaTitle: "Giotto",
        rank: 1,
        commonsCategories: [
          "Paintings by Giotto di Bondone",
          "Frescos in Cappella degli Scrovegni (Padua) by Giotto",
        ],
        workArticles: [
          "Scrovegni Chapel",
          "Ognissanti Madonna",
          "Stefaneschi Triptych",
          "Badia Polyptych",
          "Saint Francis Receiving the Stigmata (Giotto)",
          "Giotto's Crucifix at Santa Maria Novella",
          "Life of Christ (Giotto)",
          "Saint Stephen (Giotto)",
        ],
        deepCategories: true,
      },
      {
        name: "Duccio di Buoninsegna",
        wikipediaTitle: "Duccio",
        rank: 2,
        commonsCategories: [
          "Paintings by Duccio di Buoninsegna",
          "Panels formerly part of Maestà by Duccio",
        ],
        workArticles: [
          "Maestà (Duccio)",
          "Rucellai Madonna",
          "Madonna and Child (Duccio, Metropolitan)",
          "Crevole Madonna",
          "Madonna and Child with Saints Polyptych",
          "Madonna with Child and Six Angels",
        ],
      },
      {
        name: "Cimabue",
        wikipediaTitle: "Cimabue",
        rank: 3,
        commonsCategories: ["Paintings by Cimabue"],
        workArticles: [
          "Santa Trinita Maestà",
          "Maestà (Cimabue)",
          "Crucifix (Cimabue, Santa Croce)",
          "Crucifix (Cimabue, Arezzo)",
          "The Mocking of Christ (Cimabue)",
          "Castelfiorentino Madonna",
        ],
        deepCategories: true,
      },
      {
        name: "Simone Martini",
        wikipediaTitle: "Simone Martini",
        rank: 4,
        commonsCategories: ["Paintings by Simone Martini"],
        workArticles: [
          "Annunciation with Saint Margaret and Saint Ansanus",
          "Maestà (Simone Martini)",
          "Guidoriccio da Fogliano at the Siege of Montemassi",
          "Saint Catherine of Alexandria Polyptych",
          "Orsini Polyptych",
        ],
      },
      {
        name: "Fra Angelico",
        wikipediaTitle: "Fra Angelico",
        rank: 5,
        commonsCategories: [
          "Paintings by Fra Angelico",
          "Frescos by Fra Angelico",
        ],
        workArticles: [
          "Annunciation (Fra Angelico, Madrid)",
          "San Marco Altarpiece",
          "Annunciation of Cortona",
          "Coronation of the Virgin (Fra Angelico, Louvre)",
          "The Last Judgment (Fra Angelico, Florence)",
          "Deposition of Christ (Fra Angelico)",
          "Fiesole Altarpiece",
          "Perugia Altarpiece",
          "Niccoline Chapel",
          "Adoration of the Magi (Fra Angelico and Filippo Lippi)",
        ],
      },
      {
        name: "Limbourg brothers",
        wikipediaTitle: "Limbourg brothers",
        rank: 6,
        commonsCategories: [
          "Très Riches Heures du Duc de Berry",
          "Belles Heures of Jean de France, Duc de Berry",
          "Limbourg brothers",
        ],
        workArticles: [
          "Très Riches Heures du Duc de Berry",
          "Belles Heures du Duc de Berry",
        ],
      },
    ],
  },
  {
    slug: "renaissance",
    name: "Renaissance",
    wikipediaTitle: "Renaissance",
    startYear: 1400,
    endYear: 1600,
    color: "#c9a45f",
    laneY: 400,
    artists: [
      {
        name: "Leonardo da Vinci",
        wikipediaTitle: "Leonardo da Vinci",
        rank: 1,
        commonsCategories: [
          "Paintings by Leonardo da Vinci",
          "Drawings by Leonardo da Vinci",
        ],
        workArticles: [
          "Mona Lisa",
          "The Last Supper (Leonardo)",
          "Vitruvian Man",
          "Lady with an Ermine",
          "Virgin of the Rocks",
          "Salvator Mundi (painting)",
          "Ginevra de' Benci",
          "The Virgin and Child with Saint Anne (Leonardo)",
          "Annunciation (Leonardo)",
          "Saint John the Baptist (Leonardo)",
          "La Belle Ferronnière",
          "Adoration of the Magi (Leonardo)",
        ],
        deepCategories: true,
      },
      {
        name: "Michelangelo",
        wikipediaTitle: "Michelangelo",
        rank: 2,
        commonsCategories: [
          "Sculptures by Michelangelo Buonarroti",
          "Paintings by Michelangelo Buonarroti",
          "Drawings by Michelangelo Buonarroti",
        ],
        workArticles: [
          "David (Michelangelo)",
          "Pietà (Michelangelo)",
          "Sistine Chapel ceiling",
          "The Creation of Adam",
          "The Last Judgment (Michelangelo)",
          "Moses (Michelangelo)",
          "Doni Tondo",
          "Bacchus (Michelangelo)",
          "Madonna of Bruges",
          "Dying Slave",
        ],
        kindDefault: "sculpture",
        deepCategories: true,
      },
      {
        name: "Raphael",
        wikipediaTitle: "Raphael",
        rank: 3,
        commonsCategories: [
          "Paintings by Raffaello Sanzio",
          "Drawings by Raffaello Sanzio",
        ],
        workArticles: [
          "The School of Athens",
          "Sistine Madonna",
          "Transfiguration (Raphael)",
          "The Marriage of the Virgin (Raphael)",
          "Portrait of Baldassare Castiglione",
          "La Fornarina",
          "Disputation of the Holy Sacrament",
          "Galatea (Raphael)",
          "Madonna della Seggiola",
          "Madonna del Prato (Raphael)",
          "Saint George and the Dragon (Raphael)",
        ],
      },
      {
        name: "Sandro Botticelli",
        wikipediaTitle: "Sandro Botticelli",
        rank: 4,
        commonsCategories: [
          "Paintings by Sandro Botticelli",
          "Drawings by Sandro Botticelli",
          "Frescos by Sandro Botticelli",
        ],
        workArticles: [
          "The Birth of Venus",
          "Primavera (Botticelli)",
          "Venus and Mars (Botticelli)",
          "Adoration of the Magi (Botticelli)",
          "The Mystical Nativity",
          "Madonna of the Magnificat",
          "Pallas and the Centaur",
          "Calumny of Apelles",
          "Portrait of a Man with a Medal of Cosimo the Elder",
          "The Return of Judith to Bethulia",
        ],
      },
      {
        name: "Titian",
        wikipediaTitle: "Titian",
        rank: 5,
        commonsCategories: ["Paintings by Titian", "Drawings by Titian"],
        workArticles: [
          "Assumption of the Virgin (Titian)",
          "Venus of Urbino",
          "Bacchus and Ariadne",
          "Sacred and Profane Love",
          "Diana and Actaeon (Titian)",
          "Pesaro Madonna",
          "Equestrian Portrait of Charles V",
          "The Rape of Europa (Titian)",
          "Pietà (Titian)",
          "Flora (Titian)",
          "Danaë (Titian paintings)",
        ],
        deepCategories: true,
      },
      {
        name: "Albrecht Dürer",
        wikipediaTitle: "Albrecht Dürer",
        rank: 6,
        commonsCategories: [
          "Paintings by Albrecht Dürer",
          "Prints by Albrecht Dürer",
          "Drawings by Albrecht Dürer",
        ],
        workArticles: [
          "Melencolia I",
          "Young Hare",
          "Knight, Death and the Devil",
          "Praying Hands (Dürer)",
          "Self-Portrait (Dürer, Munich)",
          "Adam and Eve (Dürer)",
          "The Four Apostles",
          "Dürer's Rhinoceros",
          "Great Piece of Turf",
          "Saint Jerome in His Study (Dürer)",
          "Apocalypse (Dürer)",
        ],
      },
    ],
  },
  {
    slug: "baroque",
    name: "Baroque",
    wikipediaTitle: "Baroque",
    startYear: 1600,
    endYear: 1725,
    color: "#b3543a",
    laneY: 500,
    artists: [
      {
        name: "Caravaggio",
        wikipediaTitle: "Caravaggio",
        rank: 1,
        commonsCategories: [
          "Paintings by Caravaggio",
          "Paintings by Caravaggio by title",
          "Google Art Project works by Caravaggio",
        ],
        workArticles: [
          "The Calling of Saint Matthew",
          "Judith Beheading Holofernes (Caravaggio)",
          "Medusa (Caravaggio)",
          "Bacchus (Caravaggio)",
          "The Taking of Christ (Caravaggio)",
          "Supper at Emmaus (Caravaggio, London)",
          "The Cardsharps",
          "Conversion on the Way to Damascus",
          "The Entombment of Christ (Caravaggio)",
          "Death of the Virgin (Caravaggio)",
          "The Beheading of Saint John the Baptist (Caravaggio)",
          "David with the Head of Goliath (Caravaggio, Rome)",
        ],
        deepCategories: true,
      },
      {
        name: "Rembrandt",
        wikipediaTitle: "Rembrandt",
        rank: 2,
        commonsCategories: [
          "Paintings by Rembrandt",
          "Google Art Project works by Rembrandt",
          "Etchings by Rembrandt",
        ],
        workArticles: [
          "The Night Watch",
          "The Anatomy Lesson of Dr. Nicolaes Tulp",
          "The Storm on the Sea of Galilee",
          "The Return of the Prodigal Son (Rembrandt)",
          "Self-Portrait with Two Circles",
          "The Jewish Bride",
          "Syndics of the Drapers' Guild",
          "Belshazzar's Feast (Rembrandt)",
          "Danaë (Rembrandt)",
          "Bathsheba at Her Bath (Rembrandt)",
          "Aristotle with a Bust of Homer",
          "The Abduction of Europa (Rembrandt)",
        ],
      },
      {
        name: "Johannes Vermeer",
        wikipediaTitle: "Johannes Vermeer",
        rank: 3,
        commonsCategories: [
          "Paintings by Johannes Vermeer",
          "Paintings by Johannes Vermeer by title",
          "Google Art Project works by Johannes Vermeer",
        ],
        workArticles: [
          "Girl with a Pearl Earring",
          "The Milkmaid (Vermeer)",
          "View of Delft",
          "The Art of Painting",
          "The Astronomer",
          "The Geographer",
          "Woman Holding a Balance",
          "The Lacemaker (Vermeer)",
          "The Little Street",
          "Girl Reading a Letter at an Open Window",
          "The Music Lesson",
          "Woman Reading a Letter (Vermeer)",
        ],
        deepCategories: true,
      },
      {
        name: "Peter Paul Rubens",
        wikipediaTitle: "Peter Paul Rubens",
        rank: 4,
        commonsCategories: [
          "Paintings by Peter Paul Rubens",
          "Google Art Project works by Peter Paul Rubens",
        ],
        workArticles: [
          "The Descent from the Cross (Rubens)",
          "The Elevation of the Cross (Rubens)",
          "Massacre of the Innocents (Rubens)",
          "Marie de' Medici cycle",
          "The Rape of the Daughters of Leucippus",
          "The Three Graces (Rubens, Madrid)",
          "The Garden of Love (Rubens)",
          "Samson and Delilah (Rubens)",
          "Consequences of War",
          "Daniel in the Lions' Den (Rubens)",
          "Honeysuckle Bower",
        ],
      },
      {
        name: "Diego Velázquez",
        wikipediaTitle: "Diego Velázquez",
        rank: 5,
        commonsCategories: [
          "Paintings by Diego Velázquez",
          "Paintings by Diego Velázquez by title",
          "Paintings by Diego Velázquez by museum",
        ],
        workArticles: [
          "Las Meninas",
          "The Surrender of Breda",
          "Rokeby Venus",
          "Portrait of Innocent X",
          "Las Hilanderas",
          "The Triumph of Bacchus",
          "Apollo in the Forge of Vulcan",
          "Christ Crucified (Velázquez)",
          "Old Woman Frying Eggs",
          "The Waterseller of Seville",
          "Equestrian Portrait of Philip IV",
        ],
        deepCategories: true,
      },
      {
        name: "Artemisia Gentileschi",
        wikipediaTitle: "Artemisia Gentileschi",
        rank: 6,
        commonsCategories: [
          "Paintings by Artemisia Gentileschi",
          "Paintings by Artemisia Gentileschi by museum",
          "Paintings by Artemisia Gentileschi by genre",
        ],
        workArticles: [
          "Judith Slaying Holofernes (Artemisia Gentileschi, Naples)",
          "Judith Slaying Holofernes (Artemisia Gentileschi, Florence)",
          "Self-Portrait as the Allegory of Painting",
          "Susanna and the Elders (Artemisia Gentileschi, Pommersfelden)",
          "Judith and Her Maidservant (Artemisia Gentileschi, Florence)",
          "Self-Portrait as Saint Catherine of Alexandria",
          "Mary Magdalene in Ecstasy",
          "Danaë (Artemisia Gentileschi)",
          "Lucretia (Artemisia Gentileschi, Milan)",
          "Jael and Sisera (Artemisia Gentileschi)",
        ],
        deepCategories: true,
      },
    ],
  },
  {
    slug: "rococo",
    name: "Rococo",
    wikipediaTitle: "Rococo",
    startYear: 1700,
    endYear: 1780,
    color: "#d98ba6",
    laneY: 300,
    artists: [
      {
        name: "Antoine Watteau",
        wikipediaTitle: "Antoine Watteau",
        rank: 1,
        commonsCategories: [
          "Paintings by Antoine Watteau",
          "Drawings by Antoine Watteau",
        ],
        workArticles: [
          "The Embarkation for Cythera",
          "Pierrot (Watteau)",
          "L'Enseigne de Gersaint",
          "Mezzetino (Watteau)",
          "Fêtes Vénitiennes",
          "The Embarrassing Proposal",
          "The Surprise (Watteau)",
          "Savoyard with a Marmot",
          "L'Indifférent",
          "Jupiter and Antiope (Watteau)",
          "The Faux Pas",
          "The Two Cousins",
        ],
      },
      {
        name: "Jean-Honoré Fragonard",
        wikipediaTitle: "Jean-Honoré Fragonard",
        rank: 2,
        commonsCategories: ["Paintings by Jean-Honoré Fragonard"],
        workArticles: [
          "The Swing (Fragonard)",
          "The Progress of Love",
          "The Bolt (Fragonard)",
          "A Young Girl Reading",
          "The Stolen Kiss (painting)",
          "Coresus Sacrificing Himself to Save Callirhoe",
          "Blind Man's Buff (Fragonard, 1775–1780)",
          "The See-Saw (Fragonard, Madrid)",
          "The Music Lesson (Fragonard)",
          "The Birth of Venus (Fragonard)",
          "Fantastical Portraits",
          "The Little Park",
        ],
      },
      {
        name: "François Boucher",
        wikipediaTitle: "François Boucher",
        rank: 3,
        commonsCategories: ["Paintings by François Boucher"],
        workArticles: [
          "The Triumph of Venus",
          "Portrait of Madame de Pompadour",
          "The Toilet of Venus (Boucher)",
          "The Blonde Odalisque",
          "The Rising of the Sun",
          "The Setting of the Sun",
          "Hercules and Omphale (Boucher)",
          "Venus Consoling Love",
          "The Brunette Odalisque",
          "Pompadour at Her Toilette",
          "Lovers in a Park",
          "Fishing (Boucher)",
        ],
      },
      {
        name: "Giovanni Battista Tiepolo",
        wikipediaTitle: "Giovanni Battista Tiepolo",
        rank: 4,
        commonsCategories: [
          "Paintings by Giovanni Battista Tiepolo",
          "Frescos by Giovanni Battista Tiepolo",
        ],
        workArticles: [
          "The Banquet of Cleopatra (Tiepolo)",
          "Allegory of the Planets and Continents",
          "The Immaculate Conception (Tiepolo)",
          "The Martyrdom of Saint Bartholomew (Tiepolo)",
          "Time Unveiling Truth (Tiepolo)",
          "Alexander the Great and Campaspe in the Studio of Apelles",
          "Scipio Africanus Freeing Massiva",
          "The Flight into Egypt in a Boat",
          "Henry III Received at the Villa Contarini",
          "Juno in the Clouds",
          "Deposition (Tiepolo)",
          "Saint Patrick, Bishop of Ireland",
        ],
      },
      {
        name: "Canaletto",
        wikipediaTitle: "Canaletto",
        rank: 5,
        commonsCategories: [
          "Paintings by Giovanni Antonio Canal",
          "Paintings by Giovanni Antonio Canal by museum",
        ],
        workArticles: [
          "The Stonemason's Yard",
          "A Regatta on the Grand Canal",
          "The Bucintoro at the Molo on Ascension Day",
          "Eton College (painting)",
          "Warwick Castle, East Front from the Courtyard",
          "Interior of the Rotunda at Ranelagh",
          "A View of Walton Bridge",
          "The Feast Day of Saint Roch",
          "The Pra della Valle in Padua",
          "A View of Dolo on the Brenta Canal",
          "The Arch of Septimius Severus",
        ],
      },
      {
        name: "Jean-Baptiste-Siméon Chardin",
        wikipediaTitle: "Jean Siméon Chardin",
        rank: 6,
        commonsCategories: [
          "Paintings by Jean Siméon Chardin",
          "Jean Siméon Chardin",
        ],
        workArticles: [
          "The Ray (Chardin)",
          "Soap Bubbles (Chardin)",
          "Saying Grace (Chardin)",
          "The House of Cards",
          "Boy with a Spinning-Top",
          "Girl with a Racquet",
          "The Kitchen Maid (Chardin)",
          "The Laundress (Chardin)",
          "The Buffet (Chardin)",
          "The Attributes of Music, the Arts and the Sciences",
        ],
        deepCategories: true,
      },
    ],
  },
  {
    slug: "neoclassicism",
    name: "Neoclassicism",
    wikipediaTitle: "Neoclassicism",
    startYear: 1760,
    endYear: 1830,
    color: "#7fa8a0",
    laneY: 500,
    artists: [
      {
        name: "Jacques-Louis David",
        wikipediaTitle: "Jacques-Louis David",
        rank: 1,
        commonsCategories: [
          "Paintings by Jacques-Louis David",
          "Portrait paintings by Jacques-Louis David",
          "Le Serment des Horaces by Jacques-Louis David",
        ],
        workArticles: [
          "Oath of the Horatii",
          "The Death of Marat",
          "Napoleon Crossing the Alps",
          "The Coronation of Napoleon",
          "The Death of Socrates",
          "The Intervention of the Sabine Women",
          "The Emperor Napoleon in His Study at the Tuileries",
          "The Lictors Bring to Brutus the Bodies of His Sons",
          "Portrait of Madame Récamier",
          "The Tennis Court Oath (David)",
          "Leonidas at Thermopylae",
          "Belisarius Begging for Alms",
        ],
        deepCategories: true,
      },
      {
        name: "Jean-Auguste-Dominique Ingres",
        wikipediaTitle: "Jean-Auguste-Dominique Ingres",
        rank: 2,
        commonsCategories: [
          "Paintings by Ingres",
          "Paintings by Ingres by title",
          "Portrait paintings by Ingres",
        ],
        workArticles: [
          "Grande Odalisque",
          "The Turkish Bath",
          "Portrait of Monsieur Bertin",
          "Napoleon I on His Imperial Throne",
          "The Valpinçon Bather",
          "The Apotheosis of Homer (Ingres)",
          "Oedipus and the Sphinx (Ingres)",
          "The Source (Ingres)",
          "Portrait of Madame Moitessier",
          "The Princesse de Broglie",
          "Jupiter and Thetis",
          "The Vow of Louis XIII",
        ],
        deepCategories: true,
      },
      {
        name: "Angelica Kauffman",
        wikipediaTitle: "Angelica Kauffman",
        rank: 3,
        commonsCategories: [
          "Paintings by Angelica Kauffmann",
          "Portraits by Angelica Kauffmann",
          "History paintings by Angelica Kauffmann",
        ],
        workArticles: [
          "Ariadne Abandoned by Theseus",
          "Zeuxis Selecting Models for His Painting of Helen of Troy",
          "The Sorrow of Telemachus",
          "Telemachus and the Nymphs of Calypso",
          "Penelope at Her Loom",
          "The Parting of Abelard and Heloise",
          "Virgil Reading the Aeneid to Augustus and Octavia",
          "Sappho Inspired by Love",
          "Vortigern and Rowena (painting)",
          "Cupid and the Graces",
        ],
      },
      {
        name: "Benjamin West",
        wikipediaTitle: "Benjamin West",
        rank: 4,
        commonsCategories: [
          "Paintings by Benjamin West",
          "Paintings by Benjamin West by museum",
        ],
        workArticles: [
          "The Death of General Wolfe",
          "Benjamin Franklin Drawing Electricity from the Sky",
          "Penn's Treaty with the Indians",
          "The Death of Nelson (West painting)",
          "Death on the Pale Horse",
          "Agrippina Landing at Brundisium with the Ashes of Germanicus",
          "Treaty of Paris (painting)",
          "The Battle of La Hogue",
          "Colonel Guy Johnson and Karonghyontye (Captain David Hill)",
          "The Departure of Regulus",
        ],
      },
      {
        name: "Antonio Canova",
        wikipediaTitle: "Antonio Canova",
        rank: 5,
        commonsCategories: [
          "Sculptures by Antonio Canova",
          "Busts by Antonio Canova",
          "Marble sculptures by Antonio Canova",
        ],
        workArticles: [
          "Psyche Revived by Cupid's Kiss",
          "The Three Graces (Canova)",
          "Venus Victrix (Canova)",
          "Napoleon as Mars the Peacemaker",
          "Theseus and the Minotaur (sculpture)",
          "Venus Italica",
          "Penitent Magdalene (Canova)",
          "Monument to the Royal Stuarts",
          "George Washington (Canova)",
        ],
        kindDefault: "sculpture",
      },
    ],
  },
  {
    slug: "romanticism",
    name: "Romanticism",
    wikipediaTitle: "Romanticism",
    startYear: 1780,
    endYear: 1850,
    color: "#7d6bb5",
    laneY: 700,
    artists: [
      {
        name: "Francisco Goya",
        wikipediaTitle: "Francisco Goya",
        rank: 1,
        commonsCategories: [
          "Paintings by Francisco de Goya",
          "Los Caprichos",
          "Prints by Francisco de Goya",
        ],
        workArticles: [
          "The Third of May 1808",
          "Saturn Devouring His Son",
          "The Second of May 1808",
          "La maja desnuda",
          "Charles IV of Spain and His Family",
          "The Sleep of Reason Produces Monsters",
          "Witches' Sabbath (The Great He-Goat)",
          "The Dog (Goya)",
          "La maja vestida",
          "The Parasol",
          "Los caprichos",
          "The Disasters of War",
        ],
      },
      {
        name: "Eugène Delacroix",
        wikipediaTitle: "Eugène Delacroix",
        rank: 2,
        commonsCategories: [
          "Paintings by Eugène Delacroix",
          "Drawings by Eugène Delacroix",
        ],
        workArticles: [
          "Liberty Leading the People",
          "The Death of Sardanapalus",
          "The Massacre at Chios",
          "The Barque of Dante",
          "Women of Algiers",
          "Greece on the Ruins of Missolonghi",
          "Orphan Girl at the Cemetery",
          "The Lion Hunt (Delacroix)",
          "Portrait of Frédéric Chopin and George Sand",
        ],
      },
      {
        name: "Caspar David Friedrich",
        wikipediaTitle: "Caspar David Friedrich",
        rank: 3,
        commonsCategories: ["Paintings by Caspar David Friedrich"],
        workArticles: [
          "Wanderer above the Sea of Fog",
          "The Sea of Ice",
          "The Abbey in the Oakwood",
          "The Monk by the Sea",
          "Chalk Cliffs on Rügen",
          "Cross in the Mountains",
          "Two Men Contemplating the Moon",
          "The Stages of Life",
          "Moonrise by the Sea",
        ],
      },
      {
        name: "J. M. W. Turner",
        wikipediaTitle: "J. M. W. Turner",
        rank: 4,
        commonsCategories: [
          "Paintings by Joseph Mallord William Turner",
          "Watercolor paintings by Joseph Mallord William Turner",
          "Prints by Joseph Mallord William Turner",
        ],
        workArticles: [
          "The Fighting Temeraire",
          "Rain, Steam and Speed – The Great Western Railway",
          "The Slave Ship",
          "Snow Storm: Hannibal and his Army Crossing the Alps",
          "The Burning of the Houses of Lords and Commons",
          "Dido building Carthage",
          "Norham Castle, Sunrise",
          "Ulysses Deriding Polyphemus",
          "Modern Rome – Campo Vaccino",
        ],
      },
      {
        name: "Théodore Géricault",
        wikipediaTitle: "Théodore Géricault",
        rank: 5,
        commonsCategories: ["Paintings by Théodore Géricault"],
        workArticles: [
          "The Raft of the Medusa",
          "The Charging Chasseur",
          "The Wounded Cuirassier",
          "Portrait of a Kleptomaniac",
          "Monomaniac of Envy",
          "The 1821 Derby at Epsom",
          "Evening: Landscape with an Aqueduct",
        ],
      },
      {
        name: "William Blake",
        wikipediaTitle: "William Blake",
        rank: 6,
        commonsCategories: [
          "Paintings by William Blake",
          "Watercolor paintings by William Blake",
          "Works by William Blake by name",
        ],
        workArticles: [
          "The Ancient of Days",
          "Newton (Blake)",
          "The Ghost of a Flea",
          "Nebuchadnezzar (Blake)",
          "The Great Red Dragon paintings",
          "Pity (William Blake)",
          "The Night of Enitharmon's Joy",
          "Songs of Innocence and of Experience",
          "The Marriage of Heaven and Hell",
          "Europe a Prophecy",
          "America a Prophecy",
        ],
      },
    ],
  },
  {
    slug: "realism",
    name: "Realism",
    wikipediaTitle: "Realism (art movement)",
    startYear: 1840,
    endYear: 1880,
    color: "#8a7350",
    laneY: 400,
    artists: [
      {
        name: "Gustave Courbet",
        wikipediaTitle: "Gustave Courbet",
        rank: 1,
        commonsCategories: [
          "Paintings by Gustave Courbet",
          "Drawings by Gustave Courbet",
        ],
        workArticles: [
          "A Burial at Ornans",
          "The Stone Breakers",
          "The Painter's Studio",
          "L'Origine du monde",
          "Le Désespéré",
          "The Wounded Man (painting)",
          "The Meeting (Courbet)",
          "Le Sommeil",
          "After Dinner at Ornans",
          "Woman with a Parrot (Courbet)",
          "The Wave (Courbet)",
        ],
      },
      {
        name: "Jean-François Millet",
        wikipediaTitle: "Jean-François Millet",
        rank: 2,
        commonsCategories: [
          "Paintings by Jean-François Millet (II)",
          "Drawings by Jean-François Millet (II)",
          "Pastels by Jean-François Millet (II)",
        ],
        workArticles: [
          "The Gleaners",
          "The Angelus (painting)",
          "The Sower (Millet)",
          "Man with a Hoe",
          "The Winnower (Millet)",
          "Shepherdess with her Flock",
        ],
      },
      {
        name: "Ilya Repin",
        wikipediaTitle: "Ilya Repin",
        rank: 3,
        commonsCategories: [
          "Paintings by Ilya Yefimovich Repin",
          "Drawings by Ilya Yefimovich Repin",
        ],
        workArticles: [
          "Barge Haulers on the Volga",
          "Reply of the Zaporozhian Cossacks",
          "Ivan the Terrible and His Son Ivan",
          "Religious Procession in Kursk Governorate",
          "They Did Not Expect Him",
          "Sadko (painting)",
          "Portrait of M. P. Mussorgsky",
          "Ceremonial Sitting of the State Council on 7 May 1901 Marking the Centenary of its Foundation",
        ],
      },
      {
        name: "Winslow Homer",
        wikipediaTitle: "Winslow Homer",
        rank: 4,
        commonsCategories: [
          "Paintings by Winslow Homer",
          "Watercolor paintings by Winslow Homer",
        ],
        workArticles: [
          "The Gulf Stream (painting)",
          "Snap the Whip",
          "Breezing Up (A Fair Wind)",
          "The Fog Warning",
          "Eight Bells (painting)",
          "The Life Line (painting)",
          "Northeaster (painting)",
          "The Fox Hunt (painting)",
          "Right and Left",
          "The Veteran in a New Field",
          "Prisoners from the Front",
          "Lost on the Grand Banks",
        ],
      },
      {
        name: "Honoré Daumier",
        wikipediaTitle: "Honoré Daumier",
        rank: 5,
        commonsCategories: [
          "Lithographs by Honoré Daumier",
          "Paintings by Honoré Daumier",
          "Prints by Honoré Daumier",
        ],
        workArticles: [
          "The Third-Class Carriage",
          "The Laundress (Daumier)",
          "The Chess Players (Daumier)",
          "The Republic (Daumier)",
        ],
        kindDefault: "print",
      },
      {
        name: "Rosa Bonheur",
        wikipediaTitle: "Rosa Bonheur",
        rank: 6,
        commonsCategories: [
          "Paintings by Rosa Bonheur",
          "Drawings by Rosa Bonheur",
          "Sculptures by Rosa Bonheur",
        ],
        workArticles: [
          "The Horse Fair",
          "Ploughing in the Nivernais",
          "Weaning the Calves",
        ],
      },
    ],
  },
  {
    slug: "impressionism",
    name: "Impressionism",
    wikipediaTitle: "Impressionism",
    startYear: 1860,
    endYear: 1895,
    color: "#b48ec4",
    laneY: 500,
    artists: [
      {
        name: "Claude Monet",
        wikipediaTitle: "Claude Monet",
        rank: 1,
        commonsCategories: [
          "Paintings by Claude Monet",
          "Paintings by Claude Monet by title",
          "Framed paintings by Monet",
        ],
        workArticles: [
          "Impression, Sunrise",
          "Water Lilies (Monet series)",
          "Woman with a Parasol – Madame Monet and Her Son",
          "Haystacks (Monet series)",
          "Rouen Cathedral (Monet series)",
          "The Magpie (Monet)",
          "Garden at Sainte-Adresse",
          "Women in the Garden",
          "Poplars (Monet series)",
          "Boulevard des Capucines (Monet)",
          "La Grenouillère (Monet)",
          "Arrival of the Normandy Train, Gare Saint-Lazare",
        ],
        deepCategories: true,
      },
      {
        name: "Pierre-Auguste Renoir",
        wikipediaTitle: "Pierre-Auguste Renoir",
        rank: 2,
        commonsCategories: [
          "Paintings by Pierre-Auguste Renoir",
          "Works by Pierre-Auguste Renoir by Fezzi number",
          "Paintings by Pierre-Auguste Renoir by title",
        ],
        workArticles: [
          "Bal du moulin de la Galette",
          "Luncheon of the Boating Party",
          "Dance at Bougival",
          "La Loge",
          "The Swing (Renoir)",
          "Dance in the City",
          "Dance in the Country",
          "Girls at the Piano",
          "Les Grandes Baigneuses (Renoir)",
          "Pink and Blue (Renoir)",
          "La Grenouillère (Renoir)",
          "A Girl with a Watering Can",
        ],
      },
      {
        name: "Edgar Degas",
        wikipediaTitle: "Edgar Degas",
        rank: 3,
        commonsCategories: [
          "Paintings by Edgar Degas",
          "Sculptures by Edgar Degas",
          "Pastels by Edgar Degas",
        ],
        workArticles: [
          "The Ballet Class (Degas, Musée d'Orsay)",
          "L'Absinthe",
          "Little Dancer of Fourteen Years",
          "The Dance Class (Degas, Metropolitan Museum of Art)",
          "Miss La La at the Cirque Fernando",
          "A Cotton Office in New Orleans",
          "Place de la Concorde (Degas)",
          "The Orchestra at the Opera",
          "Young Spartans Exercising",
          "The Millinery Shop",
          "Interior (Degas)",
        ],
        deepCategories: true,
        notes:
          "Paintings are PD; photos of his sculptures (e.g. Little Dancer casts) are CC BY-SA — attribution required, filter museum-gallery shots.",
      },
      {
        name: "Berthe Morisot",
        wikipediaTitle: "Berthe Morisot",
        rank: 4,
        commonsCategories: [
          "Paintings by Berthe Morisot",
          "Paintings by Berthe Morisot in private collections",
          "Paintings by Berthe Morisot by museum",
        ],
        workArticles: [
          "The Cradle (Morisot)",
          "Summer's Day",
          "Woman at her Toilette",
          "Eugène Manet on the Isle of Wight",
          "The Harbor at Lorient",
          "In the Dining Room",
          "The Mother and Sister of the Artist",
          "The Psyche Mirror",
          "Young Girl in a Park",
          "In a Park",
        ],
      },
      {
        name: "Édouard Manet",
        wikipediaTitle: "Édouard Manet",
        rank: 5,
        commonsCategories: [
          "Paintings by Édouard Manet",
          "Paintings by Édouard Manet by title",
          "Framed paintings by Manet",
        ],
        workArticles: [
          "Olympia (Manet)",
          "Le Déjeuner sur l'herbe",
          "A Bar at the Folies-Bergère",
          "Music in the Tuileries",
          "The Execution of Emperor Maximilian",
          "The Balcony (Manet)",
          "The Railway",
          "Boating (Manet)",
          "In the Conservatory",
          "The Old Musician",
          "Berthe Morisot with a Bouquet of Violets",
        ],
      },
      {
        name: "Camille Pissarro",
        wikipediaTitle: "Camille Pissarro",
        rank: 6,
        commonsCategories: [
          "Paintings by Camille Pissarro",
          "Paintings by Camille Pissarro by year",
          "Framed paintings by Pissarro",
        ],
        workArticles: [
          "Le Boulevard de Montmartre, matinée de printemps",
          "Boulevard Montmartre, Mardi Gras",
          "The Garden of the Tuileries on a Winter Afternoon",
          "La Place du Théâtre Français",
          "Pont Boieldieu in Rouen, Rainy Weather",
          "Rue Saint-Honoré in the Afternoon. Effect of Rain",
          "Hay Harvest at Éragny",
          "Lordship Lane Station, Dulwich",
          "The Louvre, Foggy Morning",
          "Côte des Bœufs at L'Hermitage",
        ],
      },
    ],
  },
  {
    slug: "post-impressionism",
    name: "Post-Impressionism",
    wikipediaTitle: "Post-Impressionism",
    startYear: 1885,
    endYear: 1910,
    color: "#e08b4e",
    laneY: 300,
    artists: [
      {
        name: "Vincent van Gogh",
        wikipediaTitle: "Vincent van Gogh",
        rank: 1,
        commonsCategories: [
          "Paintings by Vincent van Gogh",
          "Drawings by Vincent van Gogh",
        ],
        workArticles: [
          "The Starry Night",
          "Sunflowers (Van Gogh series)",
          "The Potato Eaters",
          "Café Terrace at Night",
          "Bedroom in Arles",
          "Irises (painting)",
          "Wheatfield with Crows",
          "Self-Portrait with Bandaged Ear",
          "Portrait of Dr. Gachet",
          "Starry Night Over the Rhône",
          "The Night Café",
          "Almond Blossoms",
        ],
        deepCategories: true,
      },
      {
        name: "Paul Cézanne",
        wikipediaTitle: "Paul Cézanne",
        rank: 2,
        commonsCategories: ["Paintings by Paul Cézanne"],
        workArticles: [
          "The Card Players",
          "The Bathers (Cézanne)",
          "The Basket of Apples",
          "Mont Sainte-Victoire (Cézanne)",
          "The Boy in the Red Vest",
          "Pyramid of Skulls",
          "The Hanged Man's House",
          "A Modern Olympia",
          "Rideau, Cruchon et Compotier",
        ],
      },
      {
        name: "Paul Gauguin",
        wikipediaTitle: "Paul Gauguin",
        rank: 3,
        commonsCategories: [
          "Paintings by Paul Gauguin",
          "Sculptures by Paul Gauguin",
          "Prints by Paul Gauguin",
        ],
        workArticles: [
          "Where Do We Come From? What Are We? Where Are We Going?",
          "The Yellow Christ",
          "Vision After the Sermon",
          "Spirit of the Dead Watching",
          "When Will You Marry?",
          "Two Tahitian Women",
          "Ia Orana Maria",
          "The Green Christ",
          "Tahitian Women on the Beach",
          "Nevermore (Gauguin)",
          "Arearea",
        ],
      },
      {
        name: "Georges Seurat",
        wikipediaTitle: "Georges Seurat",
        rank: 4,
        commonsCategories: [
          "Paintings by Georges Seurat",
          "Drawings by Georges Seurat",
        ],
        workArticles: [
          "A Sunday Afternoon on the Island of La Grande Jatte",
          "Bathers at Asnières",
          "The Circus (Seurat)",
          "Le Chahut",
          "Parade de cirque",
          "Models (painting)",
          "Young Woman Powdering Herself (Seurat)",
          "The Channel of Gravelines, Petit Fort Philippe",
        ],
      },
      {
        name: "Henri de Toulouse-Lautrec",
        wikipediaTitle: "Henri de Toulouse-Lautrec",
        rank: 5,
        commonsCategories: [
          "Paintings by Henri de Toulouse-Lautrec",
          "Lithographs by Henri de Toulouse-Lautrec",
          "Posters by Henri de Toulouse-Lautrec",
        ],
        workArticles: [
          "At the Moulin Rouge",
          "Moulin Rouge: La Goulue",
          "At the Moulin Rouge, The Dance",
          "Le Lit (Toulouse-Lautrec)",
          "Divan Japonais (lithograph)",
          "La Blanchisseuse (Toulouse-Lautrec)",
          "The Hangover (Suzanne Valadon)",
          "Portrait of Vincent van Gogh (1887)",
          "La Toilette (Toulouse-Lautrec)",
          "The Englishman at the Moulin Rouge",
          "Count Alphonse de Toulouse-Lautrec Driving His Mail-Coach",
        ],
      },
      {
        name: "Henri Rousseau",
        wikipediaTitle: "Henri Rousseau",
        rank: 6,
        commonsCategories: [
          "Paintings by Henri Rousseau",
          "Drawings by Henri Rousseau",
        ],
        workArticles: [
          "The Sleeping Gypsy",
          "Tiger in a Tropical Storm",
          "The Dream (Rousseau)",
          "The Snake Charmer (Rousseau)",
          "The Hungry Lion Throws Itself on the Antelope",
          "The Repast of the Lion",
          "Boy on the Rocks",
          "Myself, Portrait-Landscape",
          "The Muse Inspiring the Poet",
          "Portrait of Mr. X (Pierre Loti)",
          "The Banks of the Bièvre near Bicêtre",
        ],
      },
    ],
  },
  {
    slug: "expressionism",
    name: "Expressionism",
    wikipediaTitle: "Expressionism",
    startYear: 1905,
    endYear: 1935,
    color: "#cf4f66",
    laneY: 600,
    artists: [
      {
        name: "Edvard Munch",
        wikipediaTitle: "Edvard Munch",
        rank: 1,
        commonsCategories: [
          "Paintings by Edvard Munch",
          "Prints by Edvard Munch",
          "Works by Edvard Munch",
        ],
        workArticles: [
          "The Scream",
          "Madonna (Munch)",
          "The Sick Child (Munch)",
          "The Dance of Life (Munch)",
          "Love and Pain (Munch)",
          "Anxiety (Munch)",
          "Ashes (Munch)",
          "Jealousy (Munch)",
          "Puberty (Munch)",
          "Self-Portrait with Cigarette",
          "Starry Night (Munch)",
          "Young Girls on a Bridge",
        ],
        notes:
          "Died 1944, but all famous works are pre-1929, so PD in the US and source country.",
      },
      {
        name: "Ernst Ludwig Kirchner",
        wikipediaTitle: "Ernst Ludwig Kirchner",
        rank: 2,
        commonsCategories: [
          "Paintings by Ernst Ludwig Kirchner",
          "Drawings by Ernst Ludwig Kirchner",
          "Prints by Ernst Ludwig Kirchner",
        ],
        workArticles: [
          "Street, Berlin (Kirchner)",
          "Berlin Street Scene",
          "Self-Portrait as a Soldier",
          "Street scenes (Ernst Kirchner artworks)",
          "Portrait of Erna Schilling",
          "Five Bathing Women at a Lake",
          "The Red Tower in Halle",
          "Archers (Kirchner)",
          "The Bridge near Wiesen",
          "Alpine Kitchen",
          "Female Half-Length Nude with Hat",
        ],
        deepCategories: true,
        notes:
          "Died 1938; the famous street-scene works are pre-1929 and PD.",
      },
      {
        name: "Franz Marc",
        wikipediaTitle: "Franz Marc",
        rank: 3,
        commonsCategories: [
          "Paintings by Franz Marc",
          "Watercolor paintings by Franz Marc",
          "Drawings by Franz Marc",
        ],
        workArticles: [
          "Yellow Cow",
          "The Tower of Blue Horses",
          "Fate of the Animals",
          "Blue Horse I",
          "Blue Horses",
          "The Foxes (Marc)",
          "Fox (Marc)",
          "Little Blue Horse",
          "Horses in Landscape",
          "Two Women on the Hillside",
          "Hut in Dachau Moors",
          "Indersdorf",
        ],
      },
      {
        name: "Egon Schiele",
        wikipediaTitle: "Egon Schiele",
        rank: 4,
        commonsCategories: [
          "Paintings by Egon Schiele",
          "Drawings by Egon Schiele",
          "Works by Egon Schiele",
        ],
        workArticles: [
          "Portrait of Wally",
          "Death and the Maiden (Schiele)",
          "The Family (Schiele)",
          "Seated Woman with Bent Knees",
          "Dead City III",
          "Dämmernde Stadt",
          "Portrait of Edith (the artist's wife)",
        ],
        notes:
          "Fully PD (d. 1918). Many works are explicit nudes — curate for a general audience.",
      },
      {
        name: "Wassily Kandinsky",
        wikipediaTitle: "Wassily Kandinsky",
        rank: 5,
        commonsCategories: [
          "Paintings by Wassily Kandinsky",
          "Works by Wassily Kandinsky",
          "Google Art Project works by Wassily Kandinsky",
        ],
        workArticles: [
          "Composition VII",
          "Composition VI",
          "Composition X",
          "The Blue Rider (Kandinsky)",
          "Das Bunte Leben",
          "Improvisation No. 30 (Cannons)",
          "Auf Weiss II (Sur blanc II)",
          "Landscape with Red Spots",
          "Three Elements",
          "Ein Zentrum (A Centre)",
          "Upward (Kandinsky)",
          "Simple Complexity",
        ],
        deepCategories: true,
        notes:
          "Died 1944 — post-1929 works are in the URAA risk zone; spot-checked files are tagged PD.",
      },
      {
        name: "Paul Klee",
        wikipediaTitle: "Paul Klee",
        rank: 6,
        commonsCategories: [
          "Paintings by Paul Klee",
          "Drawings by Paul Klee",
          "Prints by Paul Klee",
        ],
        workArticles: [
          "Twittering Machine",
          "Angelus Novus",
          "Fish Magic",
          "Ad Parnassum",
          "Senecio (Klee)",
          "Death and Fire",
          "Insula dulcamara",
          "Cat and Bird",
          "Highway and Byways",
          "Villa R",
          "Swamp Legend",
          "In the Magic Mirror",
        ],
        deepCategories: true,
        notes:
          "Died 1940 — post-1929 works are in the URAA risk zone, but late masterpieces are hosted and marked PD.",
      },
    ],
  },
  {
    slug: "cubism",
    name: "Cubism",
    wikipediaTitle: "Cubism",
    startYear: 1907,
    endYear: 1925,
    color: "#5d9db8",
    laneY: 400,
    artists: [
      {
        name: "Juan Gris",
        wikipediaTitle: "Juan Gris",
        rank: 1,
        commonsCategories: [
          "Paintings by Juan Gris",
          "Still life paintings by Juan Gris",
          "Paintings of people by Juan Gris",
        ],
        workArticles: [
          "Still Life with Checked Tablecloth",
          "The Breakfast",
          "Harlequin with a Guitar",
          "Violin and Playing Cards on a Table",
          "The Anisette Bottle",
          "Checkerboard and Playing Cards",
          "The Fruit Bowl",
          "Juan Legua",
          "Still Life with a Guitar",
          "Still Life with a Poem",
        ],
      },
      {
        name: "Robert Delaunay",
        wikipediaTitle: "Robert Delaunay",
        rank: 2,
        commonsCategories: [
          "Paintings by Robert Delaunay",
          "Eiffel Tower by Robert Delaunay",
          "Portrait paintings by Robert Delaunay",
        ],
        workArticles: [
          "Eiffel Tower (Delaunay series)",
          "Cardiff Team",
          "Champs de Mars: The Red Tower",
          "Homage to Blériot",
          "Windows (Delaunay series)",
          "Portuguese Woman",
          "Portrait of Tristan Tzara",
          "Rhythms (Delaunay)",
          "Still Life with a Parrot",
          "Windows Open Simultaneously 1st Part, 3rd Motif",
        ],
        notes:
          "Died 1941 — core pre-1930 Cubist works PD in France and the US; a few late-1930s works may have residual URAA issues.",
      },
      {
        name: "Albert Gleizes",
        wikipediaTitle: "Albert Gleizes",
        rank: 3,
        commonsCategories: ["Paintings by Albert Gleizes"],
        workArticles: [
          "Man on a Balcony",
          "Portrait of Jacques Nayral",
          "Harvest Threshing",
          "Football Players",
          "Woman with Phlox",
          "The Bathers (Gleizes)",
          "Brooklyn Bridge (Gleizes)",
          "Woman with Animals",
          "Portrait of an Army Doctor",
          "The Hunt (Gleizes)",
          "Man in a Hammock",
          "The Publisher Eugène Figuière",
        ],
        notes:
          "Died 1953, PD in France since 2024; pre-1930 Cubist works also US-PD — avoid post-1930 works (URAA risk).",
      },
      {
        name: "Fernand Léger",
        wikipediaTitle: "Fernand Léger",
        rank: 4,
        commonsCategories: [
          "Paintings by Fernand Léger",
          "Works by Fernand Léger",
          "Google Art Project works by Fernand Léger",
        ],
        workArticles: [
          "The City (Léger)",
          "Woman with a Cat (Léger)",
          "Composition with Three Figures",
          "Man and Woman (Léger)",
          "Still Life with Candlestick",
          "The Tugboat (Léger)",
        ],
        notes:
          "PD in France only since Jan 2026; post-1930 works are URAA-vulnerable in the US — filter to pre-1930 works (~30-50 safe images).",
      },
    ],
  },
  {
    slug: "surrealism",
    name: "Surrealism",
    wikipediaTitle: "Surrealism",
    startYear: 1924,
    endYear: 1955,
    color: "#6db894",
    laneY: 300,
    artists: [
      {
        name: "Yves Tanguy",
        wikipediaTitle: "Yves Tanguy",
        rank: 1,
        commonsCategories: [
          "Paintings by Yves Tanguy",
          "Paintings by Yves Tanguy in Musée de Grenoble",
        ],
        workArticles: [
          "Mama, Papa is Wounded!",
          "At 4 O'Clock in the Summer, Hope",
          "The Palace of the Windowed Rocks",
        ],
        notes:
          "Died 1955 — French copyright expired 2026-01-01; sampled files are PD or CC BY-SA 4.0.",
      },
      {
        name: "Joan Miró",
        wikipediaTitle: "Joan Miró",
        rank: 2,
        commonsCategories: [
          "Paintings by Joan Miró",
          "Sculptures by Joan Miró",
          "Works by Joan Miró",
        ],
        workArticles: [
          "The Farm (Miró)",
          "The Tilled Field",
          "The Harlequin's Carnival",
          "Dog Barking at the Moon",
          "The Birth of the World",
          "Constellations (Miró)",
          "Dona i Ocell",
          "Still Life with Old Shoe",
          "The Reaper (Miró)",
          "May 1968 (Miró)",
          "Head of a Catalan Peasant",
          "Miró's Chicago",
        ],
        notes:
          "Died 1983 — painting files need per-file license review; public sculptures are covered by Spanish FoP.",
      },
      {
        name: "Man Ray",
        wikipediaTitle: "Man Ray",
        rank: 3,
        commonsCategories: ["Photographs by Man Ray"],
        workArticles: [
          "Le Violon d'Ingres",
          "Noire et Blanche",
          "Object to Be Destroyed",
          "Cadeau",
          "Larmes",
          "Emak Bakia",
          "L'Étoile de mer",
          "Le Retour à la raison",
        ],
        kindDefault: "photograph",
        notes:
          "Free files are pre-1930 US publications (PD); only ~20 free work images.",
      },
      {
        name: "Salvador Dalí",
        wikipediaTitle: "Salvador Dalí",
        rank: 4,
        commonsCategories: [
          "Paintings by Salvador Dalí",
          "Sculptures by Salvador Dalí",
          "Works by Salvador Dalí",
        ],
        workArticles: [
          "The Persistence of Memory",
          "Christ of Saint John of the Cross",
          "The Great Masturbator",
          "Swans Reflecting Elephants",
          "Metamorphosis of Narcissus",
          "Soft Construction with Boiled Beans (Premonition of Civil War)",
          "The Elephants",
          "Dream Caused by the Flight of a Bee Around a Pomegranate a Second Before Awakening",
          "Crucifixion (Corpus Hypercubus)",
          "The Sacrament of the Last Supper",
          "Lobster Telephone",
          "The Burning Giraffe",
        ],
        notes:
          "Free repros thin (~8-10) and some PD tags dubious (deletion risk); iconic paintings are not free — lean on sculptures/prints.",
      },
      {
        name: "Francis Picabia",
        wikipediaTitle: "Francis Picabia",
        rank: 5,
        commonsCategories: ["Paintings by Francis Picabia"],
        workArticles: [
          "Udnie",
          "The Procession, Seville",
          "Caoutchouc (painting)",
          "La Nuit Espagnole (The Spanish Night)",
          "Animal Trainer (Picabia)",
          "The Double World (Picabia)",
          "Midi (Promenade des Anglais)",
        ],
        notes:
          "Died 1953 — PD in France since 2024; many pre-1930 works are also US-PD.",
      },
    ],
  },
  {
    slug: "abstract-expressionism",
    name: "Abstract Expressionism & Postwar",
    wikipediaTitle: "Abstract expressionism",
    startYear: 1943,
    endYear: 1970,
    color: "#d9683f",
    laneY: 600,
    artists: [
      {
        name: "Alexander Calder",
        wikipediaTitle: "Alexander Calder",
        rank: 1,
        commonsCategories: [
          "Sculptures by Alexander Calder",
          "Mobiles by Alexander Calder",
          "Alexander Calder",
        ],
        workArticles: [
          "Flamingo (sculpture)",
          "La Grande Vitesse",
          "Lobster Trap and Fish Tail",
          "Cirque Calder",
          "El Sol Rojo",
          "Eagle (Calder)",
          "Flying Dragon (Calder)",
          "Four Arches",
          "Mountains and Clouds",
          "Bent Propeller",
          "Cheval Rouge",
          "Teodelapio",
        ],
        kindDefault: "sculpture",
        deepCategories: true,
        notes:
          "Flamingo original tagged PD (US no-notice); photos are CC BY-SA 3.0/4.0 or CC0.",
      },
      {
        name: "Henry Moore",
        wikipediaTitle: "Henry Moore",
        rank: 2,
        commonsCategories: [
          "Sculptures by Henry Moore",
          "Henry Moore sculptures by country",
          "Bronze sculptures by Henry Moore",
        ],
        workArticles: [
          "Nuclear Energy (sculpture)",
          "Knife Edge Two Piece 1962–65",
          "Reclining Figure (Lincoln Center)",
          "King and Queen (sculpture)",
          "Draped Seated Woman 1957–58",
          "UNESCO Reclining Figure 1957–58",
          "Large Two Forms",
          "Oval with Points",
          "Locking Piece",
          "Large Arch",
          "Three Way Piece No.2: Archer",
          "Recumbent Figure 1938",
        ],
        kindDefault: "sculpture",
        deepCategories: true,
        notes:
          "UK freedom of panorama covers his public sculptures; photos are CC BY-SA 2.0-4.0.",
      },
      {
        name: "Barbara Hepworth",
        wikipediaTitle: "Barbara Hepworth",
        rank: 3,
        commonsCategories: [
          "Sculptures by Barbara Hepworth",
          "Barbara Hepworth",
        ],
        workArticles: [
          "Single Form",
          "Winged Figure",
          "Contrapuntal Forms (Hepworth)",
          "Two Forms (Divided Circle)",
          "Squares with Two Circles",
          "Sphere with Inner Form",
          "Four-Square (Walk Through)",
          "Meridian (Hepworth)",
          "Dual Form (Hepworth)",
          "The Family of Man (Hepworth)",
          "Single Form (Eikon)",
          "Curved Form (Bryher)",
        ],
        kindDefault: "sculpture",
        deepCategories: true,
        notes:
          "UK freedom of panorama covers her public bronzes; photos are CC-licensed.",
      },
      {
        name: "Arshile Gorky",
        wikipediaTitle: "Arshile Gorky",
        rank: 4,
        commonsCategories: ["Paintings by Arshile Gorky", "Arshile Gorky"],
        workArticles: ["The Liver Is the Cock's Comb"],
        notes:
          "Died 1948 — PD in life+75 countries; US tags vary per file, so read each file's license field.",
      },
      {
        name: "Isamu Noguchi",
        wikipediaTitle: "Isamu Noguchi",
        rank: 5,
        commonsCategories: ["Isamu Noguchi"],
        workArticles: [
          "Black Sun (sculpture)",
          "Octetra",
          "Floor Frame",
          "Sinai (Noguchi)",
          "Death (statue)",
        ],
        kindDefault: "sculpture",
      },
    ],
  },
  {
    slug: "pop-art",
    name: "Pop Art & Nouveau Réalisme",
    wikipediaTitle: "Pop art",
    startYear: 1955,
    endYear: 1990,
    color: "#e0559f",
    laneY: 400,
    artists: [
      {
        name: "Niki de Saint Phalle",
        wikipediaTitle: "Niki de Saint Phalle",
        rank: 1,
        commonsCategories: [
          "Niki de Saint Phalle",
          "Nana by Niki de Saint Phalle",
          "Giardino dei Tarocchi",
        ],
        workArticles: [
          "Stravinsky Fountain",
          "Tarot Garden",
          "Sun God (statue)",
          "Queen Califia's Magical Circle",
          "Nikigator",
        ],
        kindDefault: "public_work",
        notes:
          "Italy/France sites lack FoP — prefer German-FoP (Hanover Nanas) and museum-donated images; spot-checked CC BY / CC BY-SA.",
      },
      {
        name: "Claes Oldenburg",
        wikipediaTitle: "Claes Oldenburg",
        rank: 2,
        commonsCategories: [
          "Claes Oldenburg",
          "Dropped Cone (sculpture, Cologne)",
          "Gartenschlauch (Claes Oldenburg)",
        ],
        workArticles: [
          "Spoonbridge and Cherry",
          "Clothespin (Oldenburg)",
          "Batcolumn",
          "Lipstick (Ascending) on Caterpillar Tracks",
          "Cupid's Span",
          "Typewriter Eraser, Scale X",
          "Big Sweep",
          "List of public art by Oldenburg and van Bruggen",
        ],
        kindDefault: "public_work",
        deepCategories: true,
        notes:
          "US-located work categories hollowed out by no-US-FoP deletions — source images from his European works (EU/UK FoP).",
      },
      {
        name: "Robert Indiana",
        wikipediaTitle: "Robert Indiana",
        rank: 3,
        commonsCategories: [
          "Love by Robert Indiana",
          "Robert Indiana",
          "Variations on Love by Robert Indiana",
        ],
        workArticles: [
          "Love (image)",
          "Love (Indianapolis)",
          "Ahava",
          "List of Love sculptures",
        ],
        kindDefault: "public_work",
        notes:
          "The LOVE design is PD in the US (published without copyright notice); site photos are CC BY-SA.",
      },
      {
        name: "Eduardo Paolozzi",
        wikipediaTitle: "Eduardo Paolozzi",
        rank: 4,
        commonsCategories: [
          "Sculptures by Eduardo Paolozzi",
          "Newton (Eduardo Paolozzi)",
          "Mosaics at Tottenham Court Road tube station",
        ],
        workArticles: [
          "Newton (Paolozzi)",
          "Piscator (Paolozzi)",
          "The Artist as Hephaestus",
          "I Was a Rich Man's Plaything",
        ],
        kindDefault: "sculpture",
        deepCategories: true,
        notes:
          "UK freedom of panorama covers his public sculptures; photos spot-checked CC BY-SA.",
      },
      {
        name: "Jean Tinguely",
        wikipediaTitle: "Jean Tinguely",
        rank: 5,
        commonsCategories: [
          "Jean Tinguely",
          "Tinguely-Brunnen (Basel)",
          "Heureka (Jean Tinguely)",
        ],
        workArticles: [
          "Homage to New York",
          "Metamatic",
          "Chaos I",
          "Stravinsky Fountain",
        ],
        kindDefault: "public_work",
        notes:
          "Swiss freedom of panorama covers the Basel/Zurich works; spot-checked CC BY.",
      },
    ],
  },
  {
    slug: "contemporary",
    name: "Contemporary",
    wikipediaTitle: "Contemporary art",
    startYear: 1970,
    endYear: 2025,
    color: "#46c8d8",
    laneY: 500,
    artists: [
      {
        name: "Antony Gormley",
        wikipediaTitle: "Antony Gormley",
        rank: 1,
        commonsCategories: [
          "Works by Antony Gormley",
          "Angel of the North",
          "Another Place",
        ],
        workArticles: [
          "Angel of the North",
          "Another Place (sculpture)",
          "Event Horizon (sculpture)",
          "Quantum Cloud",
          "Iron:Man",
          "Exposure (sculpture)",
          "One & Other",
          "Havmannen",
          "Inside Australia",
          "Transport (sculpture)",
        ],
        kindDefault: "public_work",
        deepCategories: true,
        notes:
          "UK freedom of panorama covers his permanently sited public sculptures — images genuinely free (spot-checked PD/CC).",
      },
      {
        name: "Jaume Plensa",
        wikipediaTitle: "Jaume Plensa",
        rank: 2,
        commonsCategories: [
          "Jaume Plensa",
          "Crown Fountain",
          "Dream - sculpture by Jaume Plensa in Merseyside, England",
        ],
        workArticles: [
          "Crown Fountain",
          "Dream (sculpture)",
          "Echo (sculpture)",
          "Breathing (memorial sculpture)",
          "World Voices",
          "Water's Soul",
          "Alchemist (Plensa)",
          "Dreaming (sculpture)",
          "Behind the Walls (sculpture)",
          "Tolerance (sculpture)",
          "Looking Into My Dreams, Awilda",
          "Mirall",
        ],
        kindDefault: "public_work",
        deepCategories: true,
        notes:
          "Works in FoP countries (Spain, UK, Canada) are safe; US pieces (Crown Fountain, Echo) rely on uploader CC — gate per file.",
      },
      {
        name: "Fernando Botero",
        wikipediaTitle: "Fernando Botero",
        rank: 3,
        commonsCategories: [
          "Sculptures by Fernando Botero",
          "Fernando Botero",
          "Paintings by Fernando Botero",
        ],
        workArticles: [
          "Broadgate Venus",
          "The Hand (Botero)",
          "Adam (Botero)",
          "Woman with Mirror",
          "La paloma de la paz",
          "Abu Ghraib (Botero series)",
        ],
        kindDefault: "sculpture",
        notes:
          "Paintings are NOT free (d. 2023) — curate sculptures only; photos valid via FoP in Spain/Germany/Colombia.",
      },
      {
        name: "Friedensreich Hundertwasser",
        wikipediaTitle: "Friedensreich Hundertwasser",
        rank: 4,
        commonsCategories: [
          "Buildings by Friedensreich Hundertwasser",
          "Hundertwasserhaus Wien",
          "Waldspirale Darmstadt",
        ],
        workArticles: [
          "Hundertwasserhaus",
          "Waldspirale",
          "KunstHausWien",
          "Kuchlbauer Tower",
          "Hundertwasser Toilets",
          "Hundertwasser Art Centre",
          "Uelzen station",
          "Quixote Winery",
        ],
        kindDefault: "building",
        deepCategories: true,
        notes:
          "Paintings are not free (d. 2000) — buildings only, covered by Austrian/German FoP for architecture.",
      },
      {
        name: "Ai Weiwei",
        wikipediaTitle: "Ai Weiwei",
        rank: 5,
        commonsCategories: [
          "Ai Weiwei",
          "Ai Weiwei's Sunflower Seeds, Tate Modern",
          "Circle of Animals-Zodiac Heads",
        ],
        workArticles: [
          "Sunflower Seeds (artwork)",
          "Dropping a Han Dynasty Urn",
          "Circle of Animals/Zodiac Heads",
          "Fountain of Light",
          "Dogs That Cannot Touch Each Other",
          "Human Flow",
          "Beijing National Stadium",
        ],
        kindDefault: "sculpture",
        notes:
          "No FoP for US/China installations — license-gate every file; category diluted with artist portraits (~60-80 usable).",
      },
    ],
  },
];
